React accordion component
KiraHike/c0121-code-solutions pull request #126
Opened 2021-03-29 01:59 UTC by KiraHike

![image](https://user-images.githubusercontent.com/73143959/112777704-bae20200-8ff7-11eb-9769-b4feac87ff77.png)

2021-03-29 15:44 UTC, thebearingedge requested changes
Great, just one small change.

2021-03-29 15:44 UTC, thebearingedge commented on react-accordion-component/src/accordian.jsx
> +  }
These should be passed into the component via props (in `index.jsx`).

2021-03-31 20:27 UTC, KiraHike commented
revised

2021-03-31 20:29 UTC, thebearingedge approved these changes
👏

2021-03-31 20:29 UTC, merged