Working with collections
KiraHike/c0121-code-solutions pull request #71
Opened 2021-02-20 05:52 UTC by KiraHike

![image](https://user-images.githubusercontent.com/73143959/108585309-a6c22b00-72fc-11eb-8129-1b4366ce7000.png)

2021-02-21 21:03 UTC, thebearingedge requested changes
Nice! One small change.

2021-02-21 21:03 UTC, thebearingedge commented on working-with-collections/main.js
> +var deck = [
Try to generate your deck with loops instead of manually typing it all out.

2021-02-27 22:09 UTC, KiraHike commented
Made requested revision

2021-03-01 16:53 UTC, thebearingedge approved these changes

2021-03-02 18:02 UTC, merged